/**
 * @packageDocumentation
 * @module api.functional.internal
 */
//================================================================
import { AesPkcs5, Fetcher, Primitive } from "nestia-fetcher";
import type { IConnection } from "nestia-fetcher";

import type { ITossPaymentWebhook } from "./../../structures/ITossPaymentWebhook";
import type { ITossPayment } from "./../../structures/ITossPayment";

/**
 * 웹훅 이벤트 더미 리스너.
 * 
 * `internal.webhook` 은 실제 토스 페이먼츠의 결제 서버에는 존재하지 않는 API 로써,
 * `fake-toss-payments-server` 의 {@link  Configuration.WEBHOOK_URL } 에 아무런 URL 을 
 * 설정하지 않으면, `fake-toss-payments-server` 로부터 발생하는 모든 종류의 웹훅 
 * 이벤트는 이 곳으로 전달되어 무의미하게 사라진다.
 * 
 * 따라서 `fake-toss-payments-server` 를 사용하여 토스 페이먼츠 서버와의 연동을 미리
 * 검증코자 할 때는, 반드시 {@link  Configuration.WEBHOOK_URL } 를 설정하여 웹훅 
 * 이벤트가 귀하의 백엔드 서버로 제대로 전달되도록 하자.
 * 
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param input 웹훅 이벤트 정보
 * @author Jeongho Nam - https://github.com/samchon
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller FakeTossInternalController.webhook()
 * @path POST /internal/webhook
 */
export function webhook
    (
        connection: IConnection,
        input: Primitive<webhook.Input>
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        webhook.ENCRYPTED,
        webhook.METHOD,
        webhook.path(),
        input
    );
}
export namespace webhook
{
    export type Input = Primitive<ITossPaymentWebhook>;

    export const METHOD = "POST" as const;
    export const PATH: string = "/internal/webhook";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/internal/webhook`;
    }
}

/**
 * 가상 계좌에 입금하기.
 * 
 * `internal.virtual_accounts.deposit` 은 실제 토스 페이먼츠의 결제 서버에는 존재하지
 * 않는 API 로써, 가상 계좌 결제를 신청한 고객이, 이후 가상 계좌에 목표 금액을 입금하는 
 * 상황을 시뮬레이션할 수 있는 함수이다. 
 * 
 * 즉 `internal.virtual_accounts.deposit` 는 고객이 스스로에게 가상으로 발급된 계좌에 
 * 입금을 하고, 그에 따라 토스 페이먼츠 서버에서 webhook 이벤트가 발생하여 이를 귀하의 
 * 백엔드 서버로 전송하는 일련의 상황을 테스트하기 위한 함수인 셈이다.
 * 
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param paymentKey 대상 가상 계좌 결제 정보의 {@link ITossPayment.paymentKey}
 * @returns 입금 완료된 가상 꼐좌 결제 정보
 * @author Jeongho Nam - https://github.com/samchon
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller FakeTossInternalController.deposit()
 * @path GET /internal/:paymentKey/deposit
 */
export function deposit
    (
        connection: IConnection,
        paymentKey: string
    ): Promise<deposit.Output>
{
    return Fetcher.fetch
    (
        connection,
        deposit.ENCRYPTED,
        deposit.METHOD,
        deposit.path(paymentKey)
    );
}
export namespace deposit
{
    export type Output = Primitive<ITossPayment>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/internal/:paymentKey/deposit";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(paymentKey: string): string
    {
        return `/internal/${paymentKey}/deposit`;
    }
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;