/**
 * @packageDocumentation
 * @module api.functional.receipts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IIamportReceipt } from "../../structures/IIamportReceipt";
import type { IIamportResponse } from "../../structures/IIamportResponse";
import { NestiaSimulator } from "../../utils/NestiaSimulator";

/**
 * 현금 영수증 조회하기.
 * 
 * @param imp_uid 귀속 결제의 {@link IIamportPayment.imp_uid}
 * @returns 현금 영수증 정보
 * @security bearer
 * @author Samchon
 * 
 * @controller FakeIamportReceiptsController.at
 * @path GET /receipts/:imp_uid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
    connection: IConnection,
    imp_uid: string,
): Promise<at.Output> {
    return !!connection.simulate
        ? at.simulate(
              connection,
              imp_uid,
          )
        : PlainFetcher.fetch(
              connection,
              {
                  ...at.METADATA,
                  path: at.path(imp_uid),
              } as const,
          );
}
export namespace at {
    export type Output = Primitive<IIamportResponse<IIamportReceipt>>;

    export const METADATA = {
        method: "GET",
        path: "/receipts/:imp_uid",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (imp_uid: string): string => {
        return `/receipts/${encodeURIComponent(imp_uid ?? "null")}`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IIamportResponse<IIamportReceipt>> =>
        typia.random<Primitive<IIamportResponse<IIamportReceipt>>>(g);
    export const simulate = async (
        connection: IConnection,
        imp_uid: string,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(imp_uid),
            contentType: "application/json",
        });
        assert.param("imp_uid")(() => typia.assert(imp_uid));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * 현금 영수증 발행하기.
 * 
 * @param imp_uid 귀속 결제의 {@link IIamportPayment.imp_uid}
 * @param input 현금 영수증 입력 정보
 * @returns 현금 영수증 정보
 * @security bearer
 * @author Samchon
 * 
 * @controller FakeIamportReceiptsController.create
 * @path POST /receipts/:imp_uid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
    connection: IConnection,
    imp_uid: string,
    input: create.Input,
): Promise<create.Output> {
    return !!connection.simulate
        ? create.simulate(
              connection,
              imp_uid,
              input,
          )
        : PlainFetcher.fetch(
              {
                  ...connection,
                  headers: {
                      ...(connection.headers ?? {}),
                      "Content-Type": "application/json",
                  },
              },
              {
                  ...create.METADATA,
                  path: create.path(imp_uid),
              } as const,
              input,
          );
}
export namespace create {
    export type Input = Primitive<IIamportReceipt.ICreate>;
    export type Output = Primitive<IIamportResponse<IIamportReceipt>>;

    export const METADATA = {
        method: "POST",
        path: "/receipts/:imp_uid",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (imp_uid: string): string => {
        return `/receipts/${encodeURIComponent(imp_uid ?? "null")}`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IIamportResponse<IIamportReceipt>> =>
        typia.random<Primitive<IIamportResponse<IIamportReceipt>>>(g);
    export const simulate = async (
        connection: IConnection,
        imp_uid: string,
        input: create.Input,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(imp_uid),
            contentType: "application/json",
        });
        assert.param("imp_uid")(() => typia.assert(imp_uid));
        assert.body(() => typia.assert(input));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}

/**
 * 현금 영수증 취소하기.
 * 
 * @param imp_uid 귀속 결제의 {@link IIamportPayment.imp_uid}
 * @returns 취소된 현금 영수증 정보
 * @security bearer
 * @author Samchon
 * 
 * @controller FakeIamportReceiptsController.erase
 * @path DELETE /receipts/:imp_uid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
    connection: IConnection,
    imp_uid: string,
): Promise<erase.Output> {
    return !!connection.simulate
        ? erase.simulate(
              connection,
              imp_uid,
          )
        : PlainFetcher.fetch(
              connection,
              {
                  ...erase.METADATA,
                  path: erase.path(imp_uid),
              } as const,
          );
}
export namespace erase {
    export type Output = Primitive<IIamportResponse<IIamportReceipt>>;

    export const METADATA = {
        method: "DELETE",
        path: "/receipts/:imp_uid",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (imp_uid: string): string => {
        return `/receipts/${encodeURIComponent(imp_uid ?? "null")}`;
    }
    export const random = (g?: Partial<typia.IRandomGenerator>): Primitive<IIamportResponse<IIamportReceipt>> =>
        typia.random<Primitive<IIamportResponse<IIamportReceipt>>>(g);
    export const simulate = async (
        connection: IConnection,
        imp_uid: string,
    ): Promise<Output> => {
        const assert = NestiaSimulator.assert({
            method: METADATA.method,
            host: connection.host,
            path: path(imp_uid),
            contentType: "application/json",
        });
        assert.param("imp_uid")(() => typia.assert(imp_uid));
        return random(
            typeof connection.simulate === 'object' &&
                connection.simulate !== null
                ? connection.simulate
                : undefined
        );
    }
}