/**
 * @packageDocumentation
 * @module api.functional.payments.histories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { EncryptedFetcher } from "@nestia/fetcher/lib/EncryptedFetcher";
import type { Format } from "typia/lib/tags/Format";

import type { IPaymentCancelHistory } from "../../../structures/payments/IPaymentCancelHistory";
import type { IPaymentHistory } from "../../../structures/payments/IPaymentHistory";
import type { IPaymentSource } from "../../../structures/payments/IPaymentSource";

/**
 * 결제 내역 상세 조회하기.
 *
 * @param input 결제 내역의 원천 정보 + 비밀번호
 * @returns 결제 내역
 * @author Samchon
 *
 * @controller PaymentHistoriesController.get
 * @path PATCH /payments/histories/get
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(
  connection: IConnection,
  input: IPaymentSource.IAccessor,
): Promise<get.Output> {
  return EncryptedFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "text/plain",
      },
    },
    {
      ...get.METADATA,
      path: get.path(),
    },
    input,
  );
}
export namespace get {
  export type Input = IPaymentSource.IAccessor;
  export type Output = IPaymentHistory;

  export const METADATA = {
    method: "PATCH",
    path: "/payments/histories/get",
    request: {
      type: "text/plain",
      encrypted: true,
    },
    response: {
      type: "text/plain",
      encrypted: true,
    },
    status: null,
  } as const;

  export const path = () => "/payments/histories/get";
}

/**
 * 결제 내역 상세 조회하기.
 *
 * @param id Primary Key
 * @param input 결제 내역의 비밀번호
 * @returns 결제 내역
 * @author Samchon
 *
 * @controller PaymentHistoriesController.at
 * @path PATCH /payments/histories/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & Format<"uuid">,
  input: IPaymentSource.IPassword,
): Promise<at.Output> {
  return EncryptedFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "text/plain",
      },
    },
    {
      ...at.METADATA,
      path: at.path(id),
    },
    input,
  );
}
export namespace at {
  export type Input = IPaymentSource.IPassword;
  export type Output = IPaymentHistory;

  export const METADATA = {
    method: "PATCH",
    path: "/payments/histories/:id",
    request: {
      type: "text/plain",
      encrypted: true,
    },
    response: {
      type: "text/plain",
      encrypted: true,
    },
    status: null,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/payments/histories/${encodeURIComponent(id ?? "null")}`;
}

/**
 * 결제 내역 발행하기.
 *
 * @param input 결제 내역 입력 정보
 * @returns 결제 내역
 * @author Samchon
 *
 * @controller PaymentHistoriesController.create
 * @path POST /payments/histories
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  input: IPaymentHistory.ICreate,
): Promise<create.Output> {
  return EncryptedFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "text/plain",
      },
    },
    {
      ...create.METADATA,
      path: create.path(),
    },
    input,
  );
}
export namespace create {
  export type Input = IPaymentHistory.ICreate;
  export type Output = IPaymentHistory;

  export const METADATA = {
    method: "POST",
    path: "/payments/histories",
    request: {
      type: "text/plain",
      encrypted: true,
    },
    response: {
      type: "text/plain",
      encrypted: true,
    },
    status: null,
  } as const;

  export const path = () => "/payments/histories";
}

/**
 * 결제 취소하기.
 *
 * @param input 결제 취소 내역 입력 정보
 * @author Samchon
 *
 * @controller PaymentHistoriesController.cancel
 * @path PUT /payments/histories/cancel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function cancel(
  connection: IConnection,
  input: IPaymentCancelHistory.ICreate,
): Promise<cancel.Output> {
  return EncryptedFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "text/plain",
      },
    },
    {
      ...cancel.METADATA,
      path: cancel.path(),
    },
    input,
  );
}
export namespace cancel {
  export type Input = IPaymentCancelHistory.ICreate;
  export type Output = IPaymentHistory;

  export const METADATA = {
    method: "PUT",
    path: "/payments/histories/cancel",
    request: {
      type: "text/plain",
      encrypted: true,
    },
    response: {
      type: "text/plain",
      encrypted: true,
    },
    status: null,
  } as const;

  export const path = () => "/payments/histories/cancel";
}
