/**
 * @packageDocumentation
 * @module api.functional.v1.cash_receipts
 */
//================================================================
import { AesPkcs5 } from "./../../../__internal/AesPkcs5";
import { Fetcher } from "./../../../__internal/Fetcher";
import { Primitive } from "./../../../Primitive";
import type { IConnection } from "./../../../IConnection";

import type { ITossCashReceipt } from "./../../../structures/ITossCashReceipt";


/**
 * 현금 영수증 발행하기.
 * 
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param input 입력 정보
 * @returns 현금 영수증 정보
 * @author Jeongho Nam - https://github.com/samchon
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller FakeTossCashReceiptsController.store()
 * @path POST /v1/cash-receipts
 */
export function store
    (
        connection: IConnection,
        input: Primitive<store.Input>
    ): Promise<store.Output>
{
    return Fetcher.fetch
    (
        connection,
        store.CONFIG,
        store.METHOD,
        store.path(),
        input
    );
}
export namespace store
{
    export type Input = Primitive<ITossCashReceipt.IStore>;
    export type Output = Primitive<ITossCashReceipt>;


    export const METHOD = "POST";
    export const PATH = "/v1/cash-receipts";
    export const CONFIG = {
        input_encrypted: false,
        output_encrypted: false,
    };

    export function path(): string
    {
        return `/v1/cash-receipts`;
    }
}

/**
 * 현금 영수증 취소하기.
 * 
 * @param connection connection Information of the remote HTTP(s) server with headers (+encryption password)
 * @param receiptKey 현금 영수증의 {@link ITossCashReceipt.receiptKey}
 * @param input 취소 입력 정보
 * @returns 취소된 현금 영수증 정보
 * @author Jeongho Nam - https://github.com/samchon
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller FakeTossCashReceiptsController.cancel()
 * @path POST /v1/cash-receipts/:receiptKey/cancel
 */
export function cancel
    (
        connection: IConnection,
        receiptKey: string,
        input: Primitive<cancel.Input>
    ): Promise<cancel.Output>
{
    return Fetcher.fetch
    (
        connection,
        cancel.CONFIG,
        cancel.METHOD,
        cancel.path(receiptKey),
        input
    );
}
export namespace cancel
{
    export type Input = Primitive<ITossCashReceipt.ICancel>;
    export type Output = Primitive<ITossCashReceipt>;


    export const METHOD = "POST";
    export const PATH = "/v1/cash-receipts/:receiptKey/cancel";
    export const CONFIG = {
        input_encrypted: false,
        output_encrypted: false,
    };

    export function path(receiptKey: string): string
    {
        return `/v1/cash-receipts/${receiptKey}/cancel`;
    }
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
